export type AnimationType =
  | 'fadeIn'
  | 'slideUp'
  | 'slideDown'
  | 'slideLeft'
  | 'slideRight'
  | 'scaleIn'
  | 'bounceIn'
  | 'flipIn'
  | 'zoomIn'
  | 'rotateIn'
  | 'slideUpStagger'
  | 'scaleInStagger'
  | 'fadeInStagger'
